package year2025

import (
	"strings"
	"testing"
)

const day07Example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestDay07PartOneExample(t *testing.T) {
	AssertEqual(t, Day07PartOne, strings.NewReader(day07Example), 21)
}

func TestDay07PartOneInput(t *testing.T) {
	AssertEqual(t, Day07PartOne, ReaderForInput(7), 1658)
}

func TestDay07PartTwoExample(t *testing.T) {
	AssertEqual(t, Day07PartTwo, strings.NewReader(day07Example), 40)
}

const day07My1Example = `.......S.......
...............
.......^.......
......^.^......`

func TestDay07PartTwoMy1Example(t *testing.T) {
	AssertEqual(t, Day07PartTwo, strings.NewReader(day07My1Example), 4)
}

const day07My2Example = `.......S.......
...............
.......^.......
......^.^......`

func TestDay07PartTwoMy2Example(t *testing.T) {
	AssertEqual(t, Day07PartTwo, strings.NewReader(day07My2Example), 4)
}

const day07My3Example = `.......S.......
.......^.......
......^.^......
....1^3^3^1....` //8

func TestDay07PartTwoMy3Example(t *testing.T) {
	AssertEqual(t, Day07PartTwo, strings.NewReader(day07My3Example), 8)
}

const day07My4Example = `.......S.......
......1^1......
.....1^2^1.....
....1^3^3^1....
...1^4^331^1...` // 13

func TestDay07PartTwoMy4Example(t *testing.T) {
	AssertEqual(t, Day07PartTwo, strings.NewReader(day07My4Example), 13)
}

func TestDay07PartTwoInput(t *testing.T) {
	AssertEqual(t, Day07PartTwo, ReaderForInput(7), 53916299384254)
}
