name: 2021 Go tests

defaults:
  run:
    working-directory: "2021"

on:
  push:
    paths: "2021/**/*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
